config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: {
      sessions: 'users/sessions',
      confirmations: 'users/confirmations'
  }

=begin
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :create, :destroy, :update], defaults: { format: 'json' }
      resources :events, only: [:index, :create, :destroy, :update], defaults: { format: 'json' }
      resources :tasks, only: [:index, :create, :destroy, :update], defaults: { format: 'json' }
      resources :stands, only: [:index, :create, :destroy, :update], defaults: { format: 'json' }
      resources :reserves, only: [:index, :create, :destroy, :update], defaults: { format: 'json' }
      resources :merchants, only: [:index, :create, :destroy, :update], defaults: { format: 'json' }
    end
  end
=end

  root to: 'landing#index'

  resources :events
  #resources :stands
  resources :reserves, only: [:index,:show,:update,:edit,:destroy]
  resources :personal_informations, only: [:create, :new, :edit, :update]
  resources :merchants, only: [:index, :create, :update, :edit, :new]

  post 'events/toggle_stand_auction', to: 'events#toggle_stand_auction'
  get 'events/subscribe/:hash', to: 'events#subscribe_stand'
  get 'reserves/all/:event', to: 'reserves#all'
  get 'reserves/about_to_expire/:id', to: 'reserves#about_to_expire'
  get 'reserves/expire/:id', to: 'reserves#expire'
  post 'reserves/payment', to: 'reserves#payment'

  post 'payment_email', to: 'payments#payment_email'
  post 'payment_upload', to: 'payments#payment_upload'
  get 'payment_status/:id', to: 'payments#payment_status'
  get 'payment_toggle/:id', to: 'payments#payment_toggle'
  get 'payment_confirmation/:id', to: 'payments#payment_confirm'

  get 'mercado_payment/:id', to: 'mercado_pago#status'
  post 'mercado_pago/ipn', to: 'mercado_pago#process_notification'
  get 'mercado_pago/failure', to: 'mercado_pago#failure'
  get 'mercado_pago/success', to: 'mercado_pago#success'
  get 'mercado_pago/pending', to: 'mercado_pago#pending'
  get 'mercado_pago/payment_info/:id', to: 'mercado_pago#get_payment_info_test'

  #get 'tasks', to: 'tasks#dashboard'

  get 'users', to: 'users#index'
  get 'users/new_more', to: 'users#personal_info'

  get 'wizard/:event', to: 'step#step'
  get 'wizard/:event/edit/:step', to: 'step#edit_step'



  get 'landing/institutional', to: 'landing#institutional'
  get 'landing/events', to: 'landing#events'
  get 'landing/multimedia', to: 'landing#multimedia'
  get 'landing/contact', to: 'landing#contact'

  get 'helpers', to: 'landing#helpers'

  get 'token', to: 'mercado_pago#index'
  get 'payment/:id', to: 'mercado_pago#get_payment_info'

  post 'landing/contact', to: 'mailer#contact'

  match "/404", :to => 'errors#not_found', :via => :all
  match "/500", :to => 'errors#internal_server_error', :via => :all
  get 'errors/not_found'
  get 'errors/internal_server_error'

end

app/models/reserve.rb
class Reserve < ActiveRecord::Base
  belongs_to :stand
  belongs_to :merchant
  belongs_to :event
  belongs_to :user
  has_one :payment
end

app/controllers/api/v1/reserves_controller.rb
class Api::V1::ReservesController < Api::V1::BaseController

  def index
    respond_with Reserve.all
  end

  def create
    respond_with :api, :v1, Reserve.create(reserve_params)
  end

  def destroy
    respond_with Reserve.destroy(params[:id])
  end

  def update
    reserve = Reserve.find(params['id'])
    reserve.update_attributes(stand_params)
    respond_with reserve, json: event
  end

  private def reserve_params
    params.require(:stand).permit(:id, :merchant_id, :stand_id)
  end
end

app/controllers/reserves_controller.rb
class ReservesController < ApplicationController
  layout 'main_app'
  protect_from_forgery with: :null_session
  before_action :authenticate_user!
  before_action :check_privileges!, only:[:all,:expire,:about_to_expire]
  before_action :load_user
  include MercadoPagoHelper

  def index
    @reserves = Reserve.where(user_id: current_user.id, agreement: true)
  end

  def all
    redirect_to(reserves_path, :notice => 'Evento no encontrado') if params[:event].nil?
    @reserves = Reserve.where(event_id: params[:event])
  end

  def show
    redirect_to(reserves_path, :notice => 'Reserve Id not found') if params[:id].nil?
    @reserve = Reserve.find_by_id(params[:id])
    redirect_to(reserves_path, :notice => 'Reserve Information not found') unless @reserve
    unless @reserve.mail_sent.nil?
      redirect_to('/payment_status/'+@reserve.id.to_s) and return unless @reserve.payment_confirmation.nil?
      @stands = Stand.where(event_id: @reserve.event_id)
      @reserves = Reserve.where(event_id: @reserve.event_id)
      time = time_left @reserve.mail_sent, Time.now
      if time[:hours] <= 0 && time[:minutes] <= 0
        flash[:notice] = 'Han pasado mas de 24 desde que le enviamos el mail de seleccion de Stand, el lugar seleccionado puede que no este disponible a la hora de confirmarlo.'
      else
        flash[:notice] = 'Tiene '+time[:hours].to_s + ':'+ time[:minutes].to_s+ ' hrs de prioridad para elegir con respecto a los stands que reservaron despues de ud.'
      end
    end
  end

  def edit
    unless params[:id].nil?
      @reserve = Reserve.find_by_id params[:id]
      redirect_to(reserves_path, :notice => 'Reserve not found') unless @reserve
    end
  end

  def update
    @reserve = Reserve.find(params[:id])
    @reserve.merchant_id = Merchant.find_by_user_id(current_user.id).id
    @reserve.wait_number = Reserve.where("event_id = ? and wait_number != ?", @reserve.event.id , 0).length + 1 if params[:reserve][:wait_line] == "true"

    if @reserve.update(reserve_params)
      if request.referer.include? 'wizard'

        PandoraMailer.reserve_confirmation(@reserve, request).deliver
        flash[:notice] = 'Gracias por haber solicitado un stand para el evento '+ @reserve.event.name+' pronto le llegara una notificacion via email con los pasos a seguir.'
        redirect_to '/wizard/'+@reserve.event.id.to_s
      else
        redirect_to @reserve
      end
    else
      render 'edit'
    end
  end

  def destroy
    @reserve = Reserve.find(params[:id])
    @reserve.destroy
    redirect_to reserves_path
  end



  def payment
    @reserve = get_reserve
    redirect_to(reserves_path, :notice => 'Reserve not found') unless @reserve

    return if @reserve.nil? || !@reserve.payment_confirmation.nil?
    stand = Stand.find_by_name(params[:stand])
    return if stand.nil?
    @reserve.payment_confirmation = DateTime.now
    @reserve.stand = stand

    create_payment(stand)

    @reserve.save
    redirect_to('/payment_status/'+@reserve.id.to_s)
  end


  def about_to_expire
    @reserve = Reserve.find(params[:id])
    redirect_to(reserves_path, :notice => 'Reserve not found') unless @reserve
    PandoraMailer.reserve_about_to_expire(@reserve,request).deliver
    redirect_to ('/reserves/all/' + @reserve.event.id.to_s)
  end

  def expire
    @reserve = Reserve.find(params[:id])
    redirect_to(reserves_path, :notice => 'Reserve not found') unless @reserve
    PandoraMailer.reserve_expired_backup(@reserve,request).deliver
    @reserve.stand_id = nil
    @reserve.mail_sent = nil
    @reserve.payment_confirmation = nil
    unless @reserve.payment.nil?
      cancel_payment(@reserve.payment.mp_id) unless @reserve.payment.mp_id.nil?
      @reserve.payment.destroy
    end
    @reserve.save
    PandoraMailer.reserve_expired(@reserve,request).deliver
    redirect_to ('/reserves/all/' + @reserve.event.id.to_s)
  end

  private def create_payment(stand)
    payment = Payment.new
    payment.payment_type = params[:payment_type]
    payment.amount = stand.price
    payment.status = 'Pago no efectuado'
    payment.reserve = @reserve
    payment.save
  end

  private def get_reserve
    @reserve = Reserve.where(user_id: current_user.id, id: params[:id]).first
  end

  private def reserve_params
    params.require(:reserve).permit(:id, :payment_id, :agreement, :stand_id, :event_id, :merchant_id, :wait_number)
  end
end

app/views/reserves/_agreements.html.erb
<% if @show_warning %>
  <%= form.hidden_field :wait_line, :value => @show_warning %>
  <div class="row">
    <div class="col s12">
      <div class="card-panel red lighten-2">
            <span class="white-text">
              Por el momento hemos cubierto nuestro cupo de reservas.
              Al momento de aceptar su reserva automaticamente quedara en una lista de prioridad y en caso de que
              liberarse algun puesto nos comunicaremos con ud.
            </span>
      </div>
    </div>
  </div>
<% end %>

<div class="card-image">
  <img src="<%= asset_path ('map.jpg')%>">
</div>
<div class="card-content">

  <p>
    <a href="<%= asset_path('stands.pdf') %>" download>
      <i class="material-icons" style="top: 5px; position: relative;">file_download</i> Descargar Terminos y Condiciones
    </a>
  </p>
  <br>
  <p>
    <a href="<%= asset_path('stands.pdf')%>" target="_blank">
      <i class="material-icons" style="top: 5px; position: relative;">chrome_reader_mode</i> Leer Online Terminos y Condiciones
    </a>
  </p>
  <br>

  <div class="row">
    <div class="col s12">
      <div class="card-panel red lighten-2">
          <span class="white-text">
            Aclaracion: esto una solicitud de stand para el evento, la eleccion del lugar y el pago se realizara una
            vez finalizada la convocatoria.
          </span>
      </div>
    </div>
  </div>

  <p>
    <%= form.check_box :agreement , :required => true , id:'reserve_agreement'%>
    <%= form.label :agreement, 'He leido y acepto estos terminos y condiciones' %>
  </p>
</div>

app/views/reserves/_reserve_card.erb
<div class="col s12 l6">
  <div class="card hoverable">
    <div class="card-action ">
      <span class="card-title">Reserva #<%= reserve.id %></span>
      <p><i class="material-icons" style="position: relative; top: 5px;">date_range</i>
        <%= reserve.event.name %> - <%= reserve.event.release_date %>
      </p>

      <% unless reserve.payment_confirmation.nil? %>
        <p>Nro de Stand: <%= reserve.stand.name %></p>
        <p>Valor: <%= reserve.payment.amount %></p>
        <p>Estado: <%= reserve.payment.status %></p>
        <% unless reserve.payment.nil? || reserve.payment.payment_date.nil? %>
          <p>Su Pago ha sido acreditado. Gracias por su reserva, lo esperamos el dia del evento.</p>
        <% end %>
        <% unless show_payment_button%>
          <a class="btn-large btn-floating tooltipped halfway-fab waves-effect waves-light orange darken-1 left" data-position="bottom" data-delay="50" data-tooltip="Pagar/Ver Estado" href="<%= '/payment_status/'+reserve.id.to_s %>">
            <i class="material-icons">attach_money</i>
          </a>
        <% end %>
      <% end %>
      <% unless reserve.mail_sent.nil? || !reserve.payment_confirmation.nil? %>
        <a class="btn-large btn-floating tooltipped halfway-fab waves-effect waves-light orange darken-1 left" data-position="bottom" data-delay="50" data-tooltip="Elegir Lugar" href="<%= reserf_path(reserve) %>">
          <i class="material-icons">event_seat</i>
        </a>
      <% end %>
      <a class="btn-large btn-floating tooltipped halfway-fab waves-effect waves-light orange darken-1"
         data-confirm="Si ud. elimina esta reserva, su lugar en la cola de prioridad quedara anulado, y en caso de haber realizado el pago el reembolso sera evaluado dependiendo de la fecha de cancelacion. Esta seguro de eliminar esta reserva?" rel="nofollow" data-method="delete" data-position="bottom" data-delay="50"
         data-tooltip="Eliminar" href="<%= reserf_path(reserve) %>">
        <i class="material-icons">delete</i>
      </a>

      <a href="<%= asset_path('stands.pdf') %>" class="black-text" download>
        <i class="material-icons" style="top: 5px; position: relative;">file_download</i> Descargar Terminos y Condiciones
      </a>
      <br><br>
      <a href="<%= asset_path('map.jpg') %>" class="black-text" download>
        <i class="material-icons" style="top: 5px; position: relative;">file_download</i> Descargar Mapa
      </a>
      <br><br>

    </div>
  </div>
</div>

app/views/reserves/all.erb
<%=flash[:notice] = nil %>
<h3>Reservas realizadas</h3>
<div class="row">
  <div class="col s12">
    <table class="highlight">
      <thead>
      <tr>
        <th>ID Reserva</th>
        <th>Email</th>
        <th>Nombre</th>
        <th>Stand</th>
        <th>Lugar</th>
        <th>Tipo Pago</th>
        <th>Estado Pago</th>
        <th>Orden de Espera</th>
        <th>Acepto?</th>
        <th class="center">Enviar mail de selecion</th>
        <th class="center">Tiempo</th>
        <th class="center">Confirmar Pago</th>
        <th class="center">Tiempo</th>
        <th class="center">Recordatorio</th>
        <th class="center">Expirar</th>
        <th class="center">Eliminar</th>
      </tr>
      </thead>
      <tbody>
      <% @reserves.each do |reserve| %>
      <tr>
        <td><%= reserve.id %></td>
        <td><%= reserve.user.email %></td>
        <td><a href="<%= users_path(reserve.user)%>"><%= reserve.user.personal_information.nil? ? '-' : reserve.user.personal_information.name %></a></td>
        <td><% if !reserve.merchant.nil? %>
              <a href="<%= merchant_path(reserve.merchant)%>"> <%= reserve.merchant.store_name %></a>
            <% else %>
            -
            <% end %>
        </td>
        <td><%= reserve.stand.nil? ? '-' : reserve.stand.name %></td>
        <td><% if reserve.payment.nil? %>
            -
            <% elsif reserve.payment.payment_type == 0 %>
            Bancario
            <% else%>
            MercadoPago
            <% end %>
            </td>
        <td><%= reserve.payment.nil? ?  '-': reserve.payment.status %></td>
        <td><%= reserve.wait_number %></td>
        <td><%= reserve.agreement %></td>
        <td class="center"><a href="#" class='send-email <%=reserve.mail_sent.nil? ? "blue-text" : "red-text"%>' data-reserve="<%= reserve.id %>"><i class="material-icons">email</i></a></td>
        <td class="center">
          <% unless reserve.mail_sent.nil?
                 time = time_left reserve.mail_sent, Time.now.utc %>
            <%= time[:hours].to_s + ':'+ time[:minutes].to_s unless time[:ended]%>
          <% end %>
        </td>
        <td class="center"><a class="<%=(!reserve.payment.nil? && reserve.payment.payment_date.nil?) || reserve.payment.nil? ? "blue-text" : "red-text"%>" href="<%= '/payment_confirmation/'+ reserve.id.to_s%>"><i class="material-icons">payment</i></a></td>
        <td class="center">
          <% unless reserve.payment_confirmation.nil?
               time2 = time_left reserve.payment_confirmation, Time.now.utc
          %>
            <%= time2[:days].to_s + 'd' + time2[:hours].to_s + ':'+ time2[:minutes].to_s unless time2[:ended]%>
          <% end %>
        </td>

        <td class="center">
          <a class="blue-text" href="/reserves/about_to_expire/<%=reserve.id.to_s%>">
            <i class="material-icons">email</i>
          </a>
        </td>

        <td class="center">
          <a class="blue-text" href="/reserves/expire/<%=reserve.id.to_s%>">
            <i class="material-icons">alarm_off</i>
          </a>
        </td>

        <td class="center">
          <a class="blue-text"
             data-confirm="Si ud. elimina esta reserva, su lugar en la cola de prioridad quedara anulado, y en caso de haber realizado el pago el reembolso sera evaluado dependiendo de la fecha de cancelacion. Esta seguro de eliminar esta reserva?" rel="nofollow" data-method="delete" data-position="bottom" data-delay="50"
             data-tooltip="Eliminar" href="<%= reserf_path(reserve) %>">
            <i class="material-icons">delete</i>
          </a>
        </td>

        <%= content_tag :div, class: "hide reserve", id: 'reserve_'.concat(reserve.id.to_s), data: {reserve: reserve} do %>
        <% end %>
      </tr>
      <% end %>
      </tbody>
    </table>
  </div>

  <% if @reserves.length == 0 %>
    <div class="col s12">
      <div class="card-panel light-blue lighten-4">
        <span class="card-title">Todavia no hay reservas para este evento.</span>
      </div>
    </div>
  <% end %>
</div>

<script type="text/javascript" charset="utf-8">
    function send_email() {
        let $self = $(this);
        $.ajax({
            type: "POST",
            url: "/payment_email",
            data: {
                reserve:  $('#reserve_'+$self.data('reserve')).data('reserve')
            },
            success: function(msg){
                if (msg.status == 'mail_sent') {
                    $self.addClass('red-text');
                    $self.removeClass('blue-text');
                } else if (msg.status == 'cancelled') {
                    $self.addClass('blue-text');
                    $self.removeClass('red-text');
                }
            }
        })
    }
    $(document).ready(function () {
        $('.send-email').on('click',send_email);

    });
</script>

app/views/reserves/index.html.erb
<h3 class="hide-on-med-and-up	center">Mis Reservas</h3></span>
<div class="row">
  <% @reserves.each do |reserve| %>
   <%= render :partial => 'reserve_card', locals: {reserve: reserve, show_payment_button: !reserve.payment.nil? && !reserve.payment.payment_date.nil?} %>
  <% end %>

  <% if @reserves.length == 0 %>
    <div class="col s12">
      <div class="card-panel light-blue lighten-4">
        <span class="card-title">Todavia no has solicitado una reserva en ningun evento.</span>
      </div>
    </div>
  <% end %>
</div>

app/views/reserves/show.html.erb
<div class="row">
  <div class="col s12 l6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">Reserva #<%= @reserve.id %></span>
        <p><%= @reserve.event.name %></p>
        <p>
          <i class="material-icons" style="position: relative; top: 5px;">date_range</i>
          <%= @reserve.event.release_date %>
        </p>
      </div>
    </div>
  </div>
  <% unless @reserve.mail_sent.nil? %>
    <%= form_tag('/reserves/payment', method: 'post', local: true) do |form| %>
      <%= submit_tag 'submit', class: 'hide' %>
      <input type="hidden" name="id" value="<%= @reserve.id %>">
      <div class="col s12 l6">
      <div class="card">
        <div class="card-action select-price">
          Seleccione el area donde desea reservar su stand:
          <p>
            <input type="radio" name="stand_area" value="650" id="scenario" required data-show="scenario" data-hide="alley" checked>
            <label for="scenario">Zona Escenario - $650</label>
          </p>
          <p>
            <input type="radio" name="stand_area" value="450" id="alley" required data-show="alley" data-hide="scenario">
            <label for="alley">Zona Salas Tematicas - $450</label>
          </p>
        </div>
      </div>
    </div>

    <div class="col s12 l6">
      <div class="card">
        <div class="card-content map">
          <span class="card-title">Mapa del Evento</span>
          <div class="scenario" style="position: relative;">
            <img class="responsive-img"  src="<%= asset_path('scenario.jpg')%>" alt="" id="scenario_img">
            <input type="radio" name="stand" value="P1"  id="scenario1"  required data-img="scenario_img" data-xmin="283" data-xmax="363" data-ymin="403" data-ymax="728">
            <input type="radio" name="stand" value="P2"  id="scenario2"  required data-img="scenario_img" data-xmin="283" data-xmax="363" data-ymin="477" data-ymax="728">
            <input type="radio" name="stand" value="P3"  id="scenario3"  required data-img="scenario_img" data-xmin="283" data-xmax="363" data-ymin="550" data-ymax="728">
            <input type="radio" name="stand" value="P4"  id="scenario4"  required data-img="scenario_img" data-xmin="283" data-xmax="363" data-ymin="623" data-ymax="728">
            <input type="radio" name="stand" value="P5"  id="scenario5"  required data-img="scenario_img" data-xmin="215" data-xmax="363" data-ymin="648" data-ymax="728">
            <input type="radio" name="stand" value="P6"  id="scenario6"  required data-img="scenario_img" data-xmin="135" data-xmax="363" data-ymin="648" data-ymax="728">
            <input type="radio" name="stand" value="P7"  id="scenario7"  required data-img="scenario_img" data-xmin="55" data-xmax="363" data-ymin="648" data-ymax="728">
            <input type="radio" name="stand" value="P8"  id="scenario8"  required data-img="scenario_img" data-xmin="51" data-xmax="363" data-ymin="605" data-ymax="728">
            <input type="radio" name="stand" value="P9"  id="scenario9"  required data-img="scenario_img" data-xmin="51" data-xmax="363" data-ymin="538" data-ymax="728">
            <input type="radio" name="stand" value="P10" id="scenario10" required data-img="scenario_img" data-xmin="51" data-xmax="363" data-ymin="466" data-ymax="728">
            <input type="radio" name="stand" value="P11" id="scenario11" required data-img="scenario_img" data-xmin="51" data-xmax="363" data-ymin="394" data-ymax="728">
            <input type="radio" name="stand" value="P12" id="scenario12" required data-img="scenario_img" data-xmin="51" data-xmax="363" data-ymin="315" data-ymax="728">
          </div>
          <div class="alley" style="position: relative;">
            <img class="responsive-img" src="<%= asset_path('alley.jpg')%>" alt="" id="alley_img">
            <input type="radio" name="stand" value="N1"  id="alley1" required data-img="alley_img" data-xmin="110" data-xmax="258" data-ymin="325" data-ymax="728">
            <input type="radio" name="stand" value="N2"  id="alley2" required data-img="alley_img" data-xmin="110" data-xmax="258" data-ymin="399" data-ymax="728">
            <input type="radio" name="stand" value="N3"  id="alley3" required data-img="alley_img" data-xmin="110" data-xmax="258" data-ymin="473" data-ymax="728">
            <input type="radio" name="stand" value="N4"  id="alley4" required data-img="alley_img" data-xmin="110" data-xmax="258" data-ymin="541" data-ymax="728">
            <input type="radio" name="stand" value="N5"  id="alley5" required data-img="alley_img" data-xmin="110" data-xmax="258" data-ymin="617" data-ymax="728">
            <input type="radio" name="stand" value="N6"  id="alley6" required data-img="alley_img" data-xmin="110" data-xmax="258" data-ymin="686" data-ymax="728">
          </div>
        </div>
      </div>
    </div>

    <div class="col s12 l6">
      <div class="card">
        <div class="card-content">
          <span class="card-title">Datos del Stand Seleccionado</span>
          <p>Stand Nº: <span id="stand_id"></span></p>
          <p>Status: <span id="stand_status"></span></p>
          <p>Sector: <span id="stand_sector"></span></p>
          <p>Tienda: <span id="stand_merchant"></span></p>
          <p>Web: <span id="stand_merchant_web"></span></p>
        </div>
      </div>
    </div>
    <div class="col s12 l6">
        <div class="card">
          <div class="card-content">
            <span class="card-title">Seleccione el Metodo de Pago</span>
            <p>
              <input type="radio" name="payment_type" value="0" id="bank" required checked>
              <label for="bank">Deposito Bancario</label>
            </p>
            <p>
              <input type="radio" name="payment_type" value="1" id="mercadopago" required>
              <label for="mercadopago">Mercado Pago</label>
            </p>
            <a id="submit-button" href="#" class="btn-large btn-floating tooltipped halfway-fab waves-effect waves-light orange darken-1" data-position="bottom" data-delay="50" data-tooltip="Guardar Cambios">
              <i class="material-icons">save</i>
            </a>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>

  <%= content_tag :div, class: 'hide stands', data: {stands: @stands} do %>
  <% end %>
  <%= content_tag :div, class: 'hide reserves', data: {reserves: @reserves} do %>
  <% end %>
</div>

<style>
  .select-price {
    height: 166px;
  }

  .map label {
    position: absolute !important;
    opacity: 0 !important;
  }
  .map input {
    opacity: 1!important;
    pointer-events: all!important;
  }
  .alley {
    display:none;
  }
  .scenario{
  }
</style>

<script type="text/javascript" charset="utf-8">
  function adjust_checkbox($input,height,width, xmin,xmax,ymin,ymax) {
      $input.css('top',height*xmin/xmax);
      $input.css('left',width*ymin/ymax);
      $input.css('width', (height*2/xmax)+'em');
      $input.css('height',(width*2/ymax)+'em');
  }


  function adjust() {
      $('input[name="stand"]').each(function (i, e) {
          let $img = $('#'+$(e).data('img'))[0];
          adjust_checkbox($(e),$img.height,$img.width,$(e).data('xmin'),$(e).data('xmax'),$(e).data('ymin'),$(e).data('ymax'));
      });
  }

  function disabled_stands() {
      let reserved = $(".reserves").data('reserves');
      let stands = $(".stands").data('stands');
      console.log(reserved, stands)
      $.each(reserved, function (i,e) {
          if (e['stand_id']) {
              let stand = jQuery.grep(stands, function(obj) {
                  console.log(obj.id,e['stand_id']);
                  return obj.id === e['stand_id'];
              });
              $('input[value="'+stand[0].name+'"]').attr('disabled','disabled');
          }
      })
  }

  $(document).ready(function() {
      $('img').click(function(e) {
          let offset = $(this).offset();
          console.log('x',e.pageX - offset.left);
          console.log(this.width*470/728);
          console.log('y',e.pageY - offset.top);
          console.log(this.height*80/258);
      });

      disabled_stands();

      //$('.testo').on('click', ajust)
      $( window ).resize(adjust);
      adjust();

      $('input[name="stand_area"]').click(function(){
          $('.'+$(this).data('show')).show();
          $('.'+$(this).data('hide')).hide();
          adjust()
      });

      $('input[name="stand"]').click(function () {
          let $this = $(this)
          if ($this.attr('disabled')){
              $this.click(alert('e amigo'))
          }
      })
  });
</script>