config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: {
      sessions: 'users/sessions',
      confirmations: 'users/confirmations'
  }

=begin
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :create, :destroy, :update], defaults: { format: 'json' }
      resources :events, only: [:index, :create, :destroy, :update], defaults: { format: 'json' }
      resources :tasks, only: [:index, :create, :destroy, :update], defaults: { format: 'json' }
      resources :stands, only: [:index, :create, :destroy, :update], defaults: { format: 'json' }
      resources :reserves, only: [:index, :create, :destroy, :update], defaults: { format: 'json' }
      resources :merchants, only: [:index, :create, :destroy, :update], defaults: { format: 'json' }
    end
  end
=end

  root to: 'landing#index'

  resources :events
  #resources :stands
  resources :reserves, only: [:index,:show,:update,:edit,:destroy]
  resources :personal_informations, only: [:create, :new, :edit, :update]
  resources :merchants, only: [:index, :create, :update, :edit, :new]

  post 'events/toggle_stand_auction', to: 'events#toggle_stand_auction'
  get 'events/subscribe/:hash', to: 'events#subscribe_stand'
  get 'reserves/all/:event', to: 'reserves#all'
  get 'reserves/about_to_expire/:id', to: 'reserves#about_to_expire'
  get 'reserves/expire/:id', to: 'reserves#expire'
  post 'reserves/payment', to: 'reserves#payment'

  post 'payment_email', to: 'payments#payment_email'
  post 'payment_upload', to: 'payments#payment_upload'
  get 'payment_status/:id', to: 'payments#payment_status'
  get 'payment_toggle/:id', to: 'payments#payment_toggle'
  get 'payment_confirmation/:id', to: 'payments#payment_confirm'

  get 'mercado_payment/:id', to: 'mercado_pago#status'
  post 'mercado_pago/ipn', to: 'mercado_pago#process_notification'
  get 'mercado_pago/failure', to: 'mercado_pago#failure'
  get 'mercado_pago/success', to: 'mercado_pago#success'
  get 'mercado_pago/pending', to: 'mercado_pago#pending'
  get 'mercado_pago/payment_info/:id', to: 'mercado_pago#get_payment_info_test'

  #get 'tasks', to: 'tasks#dashboard'

  get 'users', to: 'users#index'
  get 'users/new_more', to: 'users#personal_info'

  get 'wizard/:event', to: 'step#step'
  get 'wizard/:event/edit/:step', to: 'step#edit_step'



  get 'landing/institutional', to: 'landing#institutional'
  get 'landing/events', to: 'landing#events'
  get 'landing/multimedia', to: 'landing#multimedia'
  get 'landing/contact', to: 'landing#contact'

  get 'helpers', to: 'landing#helpers'

  get 'token', to: 'mercado_pago#index'
  get 'payment/:id', to: 'mercado_pago#get_payment_info'

  post 'landing/contact', to: 'mailer#contact'

  match "/404", :to => 'errors#not_found', :via => :all
  match "/500", :to => 'errors#internal_server_error', :via => :all
  get 'errors/not_found'
  get 'errors/internal_server_error'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :merchants
end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :name, presence: true,
            length: { minimum: 2 }
  has_many :tasks
end

app/models/financial.rb
class Financial < ActiveRecord::Base
  belongs_to :user
  belongs_to :item
  belongs_to :task
end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/merchant.rb
class Merchant < ActiveRecord::Base
  belongs_to :personal_information
  belongs_to :user
  belongs_to :category
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :reserve
end

app/models/reserve.rb
class Reserve < ActiveRecord::Base
  belongs_to :stand
  belongs_to :merchant
  belongs_to :event
  belongs_to :user
  has_one :payment
end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/stand.rb
class Stand < ActiveRecord::Base
  belongs_to :event
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :event
  belongs_to :user
  belongs_to :creator, :class_name => 'User'
end

app/models/task_comment.rb
class TaskComment < ActiveRecord::Base
  belongs_to :task
  belongs_to :user
end

app/models/task_dependency.rb
class TaskDependency < ActiveRecord::Base
  belongs_to :first, :class_name => 'User'
  belongs_to :second, :class_name => 'User'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  has_one :role
  has_one :merchant
  has_one :personal_information

end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/financials_helper.rb
module FinancialsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Pandora Eventos</title>
  <%= render 'partials/head' %>
  <%= stylesheet_link_tag  'application', media: 'all'%>
  <%= javascript_include_tag 'landing', 'data-turbolinks-track' => true %>
</head>
<body>
  <div class="container">

    <header class="masthead">
      <div style="text-align: center">
        <img src="<%= asset_path('headerL.png')%>" alt="Header" class="imgHeader">
      </div>

      <nav class="navbar navbar-expand-md navbar-light rounded mb-3">
        <button class="navbar-toggler bg-light" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse"
          aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse bg-light" id="navbarCollapse">
          <ul class="navbar-nav text-md-center nav-justified w-100">
            <li class="nav-item active">
              <a class="nav-link" href="<%= root_path %>">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <%= link_to 'Institucional', '/landing/institutional', class: 'nav-link'%>
            </li>
            <li class="nav-item">
              <%= link_to 'Eventos', '/landing/events', class: 'nav-link'%>
            </li>
           <!-- <li class="nav-item">
              <%= link_to 'Multimedia', '/landing/multimedia', class: 'nav-link'%>
            </li> -->
            <li class="nav-item">
              <%= link_to 'Contacto', '/landing/contact', class: 'nav-link'%>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Acceso</a>
              <div class="dropdown-menu" aria-labelledby="dropdown01">
                <%= link_to 'Pandorapp', '/events', class: 'dropdown-item'%>
                <%= link_to 'Stands', '/merchants', class: 'dropdown-item'%>
              </div>
            </li>
          </ul>
        </div>
      </nav>
    </header>
    <% unless flash[:notice].nil? %>
      <div class="alert alert-primary" style="text-align: center">
          <span ><%= flash[:notice] %></span>
      </div>
    <% end %>
    <%= yield %>

      <!-- Site footer -->
      <footer class="footer row text-center">
        <div class="col-lg-4">
          <p class="font_9">
            <span class="color_11">© 2018 by Pandora Eventos</span>
          </p>
        </div>
        <div class="col-lg-4">
          <ul aria-label="Social bar" class="socialBar">
            <li>
              <a href="https://www.facebook.com/PandorasBoxEventos/" target="_blank" data-content="https://www.facebook.com/PandorasBoxEventos/"
                data-type="external">
                <div data-style="position:relative" >
                  <img alt="Facebook - Black Circle" data-type="image" src="<%= asset_path('fb-icon.png') %>">
                </div>
              </a>
            </li>
            <li>
              <a href="https://www.youtube.com/channel/UCN5FTq63ShiXce8w4lHqGsA" target="_blank" data-content="https://www.youtube.com/channel/UCN5FTq63ShiXce8w4lHqGsA"
                data-type="external">
                <div data-style="position:relative" >
                  <img alt="Youtube - Black Circle" data-type="image" src="<%= asset_path('yt-icon.png') %>">
                </div>
              </a>
            </li>
            <li>
              <a href="https://www.instagram.com/pandorasboxeventos/" target="_blank" data-content="https://www.instagram.com/pandorasboxeventos/"
                data-type="external">
                <div data-style="position:relative" >
                  <img alt="Instagram - Black Circle" data-type="image" src="<%= asset_path('inst-icon.png') %>">
                </div>
              </a>
            </li>
          </ul>
        </div>
        <div class="col-lg-4">

        </div>
      </footer>

  </div>
</body>

</html>

app/views/layouts/email.html.erb
<table>
  <tr>
    <td align="center">
      <img src="https://drive.google.com/uc?export=view&id=1PBjexbMVdbHI4V5UBIWgBvsx6rgWFmml"
           alt="Header" class="imgHeader" style="width: 400px;">
    </td>
  </tr>
  <tr>
    <td>
      <%= yield %>
    </td>
  </tr>
  <tr>
    <td align="center">
      <hr>
      <span>© 2018 by Pandora Eventos</span>
      <ul aria-label="Social bar" class="socialBar" style="padding: 0;">
        <li style="width: 48px;
            height: 48px;
            margin-bottom: 0px;
            margin-right: 10px;
            display: inline-block;">
          <a href="https://www.facebook.com/PandorasBoxEventos/" target="_blank" data-content="https://www.facebook.com/PandorasBoxEventos/"
             data-type="external">
            <div data-style="position:relative">
              <img alt="Facebook - Black Circle" data-type="image" src="https://drive.google.com/uc?export=view&id=1b4mJsoFTQm6GGvuv7bQNttZjLVoHp7iV"
                   style="width: 48px;
                       height: 48px;
                       object-fit: cover;">
            </div>
          </a>
        </li>
        <li style="width: 48px;
            height: 48px;
            margin-bottom: 0px;
            margin-right: 10px;
            display: inline-block;">
          <a href="https://www.youtube.com/channel/UCN5FTq63ShiXce8w4lHqGsA" target="_blank" data-content="https://www.youtube.com/channel/UCN5FTq63ShiXce8w4lHqGsA"
             data-type="external">
            <div data-style="position:relative">
              <img alt="Youtube - Black Circle" data-type="image" src="https://drive.google.com/uc?export=view&id=10j9EckGwbHCvDnCva6BMtndh4R-4SZcK"
                   style="width: 48px;
                       height: 48px;
                       object-fit: cover;">
            </div>
          </a>
        </li>
        <li style="width: 48px;
            height: 48px;
            margin-bottom: 0px;
            margin-right: 10px;
            display: inline-block;">
          <a href="https://www.instagram.com/pandorasboxeventos/" target="_blank" data-content="https://www.instagram.com/pandorasboxeventos/"
             data-type="external">
            <div data-style="position:relative">
              <img alt="Instagram - Black Circle" data-type="image" src="https://drive.google.com/uc?export=view&id=1YxnVbCOPeiQm0F1OT2jMM9XFTrPwPdG1"
                   style="width: 48px;
                       height: 48px;
                       object-fit: cover;">
            </div>
          </a>
        </li>
      </ul>
    </td>
  </tr>
</table>

app/views/layouts/errors.erb
<!DOCTYPE html>
<html>
<head>
  <%= render 'partials/head' %>
  <%= stylesheet_link_tag 'main_app', media: 'all', 'data-turbolinks-track' => true %>

  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<style>

</style>
<body>
<%= render 'partials/header' %>
<div class="row">
  <div class="col s12 m4 offset-m4">
    <div class="card red lighten-2">
      <div class="card-content">
        <%= yield %>
      </div>
    </div>
  </div>
</div>
<%= javascript_include_tag 'main_app', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/layouts/main_app.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render 'partials/head' %>
  <%= stylesheet_link_tag 'main_app', media: 'all', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<style>
  header, main, footer {
    padding-left: 300px;
  }

  @media only screen and (max-width : 992px) {
    header, main, footer {
      padding-left: 0;
    }
  }
</style>
<body>
  <header>
    <div role="navigation">
      <%= render :partial => 'partials/header', :locals => {:current_user => @user} %>
    </div>
  </header>
  <main>
    <div class="row">
      <% unless flash[:notice].nil? %>
        <div class="col s12">
          <div class="card-panel light-blue lighten-4">
            <span class="card-title"><%= flash[:notice] %></span>
          </div>
        </div>
      <% end %>
      <div class="col s12">
        <%= yield %>
      </div>
    </div>
  </main>
  <%= render :partial => 'partials/nav' %>
  <%= javascript_include_tag 'main_app', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/layouts/sessions.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render 'partials/head' %>
  <%= stylesheet_link_tag 'main_app', media: 'all', 'data-turbolinks-track' => true %>

  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<style>

</style>
<body>
  <%= render 'partials/header' %>
  <div class="row">
      <div class="col s12 m4 offset-m4">
        <div class="card">
          <div class="card-content">
            <%= yield %>
            <%= render "devise/shared/links" %>
          </div>
        </div>
      </div>
    </div>
  <%= javascript_include_tag 'main_app', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/partials/_head.html.erb
<title>PandorApp</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">
<meta property="og:title" content="Pandora Eventos" />
<meta property="og:type" content="website"/>
<meta property="og:url" content="<%= request.host %>" />
<meta property="og:image" content="<%= asset_path('socialMedia.jpg') %>" />
<meta property="og:description" content="Pandora es la organizadora de eventos por excelencia en la ciudad de Tandil. Geek-con #3 10 de mayo no te lo pierdas!!!" />
<link rel="icon" href="<%= asset_path('favicon.ico') %>">
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

<%= csrf_meta_tags %>

app/views/partials/_header.html.erb
<nav class="white-text gradient-orange" >
  <div class="nav-wrapper">
    <a class="brand-logo"></a>
    <a href="#" data-activates="slide-out" class="button-collapse"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down">
    <% unless user_signed_in? %>
      <!--
      <li><%= link_to('Login', new_user_session_path, :class => 'btn btn-primary d-flex align-items-center usr-btn')  %></li>
      -->
    <% end %>
    </ul>
  </div>
</nav>

app/views/partials/_nav.html.erb
<ul id="slide-out" class="side-nav fixed">
  <li><div class="user-view">
    <div class="background">
      <img src="<%= asset_path('userBG.jpg') %>">
    </div>
    <img class="circle" src="<%= asset_path('box.png') %>">
    <!--span class="white-text name">John Doe</span-->
    <span class="black-text text-darken-2 email"><%= @email %></span>
  </div></li>
  <li><a href="<%= users_path %>" class="waves-effect"><i class="material-icons">account_circle</i>Mi Perfil</a></li>
  <li><div class="divider"></div></li>
  <li><a href="<%= events_path %>" class="waves-effect"><i class="material-icons">event</i>Eventos</a></li>
  <li><div class="divider"></div></li>
  <li><a href="<%= merchants_path %>" class="waves-effect"><i class="material-icons">store</i>Mi Stand</a></li>
  <li><div class="divider"></div></li>
  <li><a href="<%= reserves_path %>" class="waves-effect"><i class="material-icons">confirmation_number</i>Mis Reservas</a></li>
  <li><div class="divider"></div></li>
  <li><a rel="nofollow" data-method="delete" href="<%= destroy_user_session_path %>"><i class="material-icons">exit_to_app</i>Logout</a></li>
</ul>

<script type="text/javascript" charset="utf-8">
  $(document).ready(function () {
  })
</script>