config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: {
      sessions: 'users/sessions',
      confirmations: 'users/confirmations'
  }

=begin
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :create, :destroy, :update], defaults: { format: 'json' }
      resources :events, only: [:index, :create, :destroy, :update], defaults: { format: 'json' }
      resources :tasks, only: [:index, :create, :destroy, :update], defaults: { format: 'json' }
      resources :stands, only: [:index, :create, :destroy, :update], defaults: { format: 'json' }
      resources :reserves, only: [:index, :create, :destroy, :update], defaults: { format: 'json' }
      resources :merchants, only: [:index, :create, :destroy, :update], defaults: { format: 'json' }
    end
  end
=end

  root to: 'landing#index'

  resources :events
  #resources :stands
  resources :reserves, only: [:index,:show,:update,:edit,:destroy]
  resources :personal_informations, only: [:create, :new, :edit, :update]
  resources :merchants, only: [:index, :create, :update, :edit, :new]

  post 'events/toggle_stand_auction', to: 'events#toggle_stand_auction'
  get 'events/subscribe/:hash', to: 'events#subscribe_stand'
  get 'reserves/all/:event', to: 'reserves#all'
  get 'reserves/about_to_expire/:id', to: 'reserves#about_to_expire'
  get 'reserves/expire/:id', to: 'reserves#expire'
  post 'reserves/payment', to: 'reserves#payment'

  post 'payment_email', to: 'payments#payment_email'
  post 'payment_upload', to: 'payments#payment_upload'
  get 'payment_status/:id', to: 'payments#payment_status'
  get 'payment_toggle/:id', to: 'payments#payment_toggle'
  get 'payment_confirmation/:id', to: 'payments#payment_confirm'

  get 'mercado_payment/:id', to: 'mercado_pago#status'
  post 'mercado_pago/ipn', to: 'mercado_pago#process_notification'
  get 'mercado_pago/failure', to: 'mercado_pago#failure'
  get 'mercado_pago/success', to: 'mercado_pago#success'
  get 'mercado_pago/pending', to: 'mercado_pago#pending'
  get 'mercado_pago/payment_info/:id', to: 'mercado_pago#get_payment_info_test'

  #get 'tasks', to: 'tasks#dashboard'

  get 'users', to: 'users#index'
  get 'users/new_more', to: 'users#personal_info'

  get 'wizard/:event', to: 'step#step'
  get 'wizard/:event/edit/:step', to: 'step#edit_step'



  get 'landing/institutional', to: 'landing#institutional'
  get 'landing/events', to: 'landing#events'
  get 'landing/multimedia', to: 'landing#multimedia'
  get 'landing/contact', to: 'landing#contact'

  get 'helpers', to: 'landing#helpers'

  get 'token', to: 'mercado_pago#index'
  get 'payment/:id', to: 'mercado_pago#get_payment_info'

  post 'landing/contact', to: 'mailer#contact'

  match "/404", :to => 'errors#not_found', :via => :all
  match "/500", :to => 'errors#internal_server_error', :via => :all
  get 'errors/not_found'
  get 'errors/internal_server_error'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  has_one :role
  has_one :merchant
  has_one :personal_information

end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::BaseController

  def index
    respond_with User.all
  end

  def create
    respond_with :api, :v1, User.create(user_params)
  end

  def destroy
    respond_with User.destroy(params[:id])
  end

  def update
    user = User.find(params['id'])
    user.update_attributes(user_params)
    respond_with user, json: user
  end

  private def user_params
    params.require(:user).permit(:id, :email)
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController

  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  def after_confirmation_path_for(resource_name, resource)
    events_path
    #super(resource_name, resource)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController

  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
   def new
     super
   end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController

  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'main_app'
  protect_from_forgery with: :null_session
  before_action :authenticate_user!
  before_action :load_user

  def index
      @personal_info = PersonalInformation.find_by_user_id current_user.id
  end

  def personal_info
    @data_model = PersonalInformation.new
    render 'users/new' and return
  end
end

app/views/users/_personal_info.html.erb
<% if @data_model.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@data_model.errors.count, "error") %> prohiben que estos datos sean guardados.
    </h2>
    <ul>
      <% @data_model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="input-field col s6">
  <%= form.label :name , 'Nombre', :data => {error:"wrong" , success:"right"} %>
  <%= form.text_field :name , :required => true, class: 'validate' %>
</div>

<div class="input-field col s6">
  <%= form.label :last_name , 'Apellido' , :data => {error:"wrong" , success:"right"}  %>
  <%= form.text_field :last_name , :required => true %>
</div>

<div class="input-field col s12">
  <%= form.label :dni , 'DNI' , :data => {error:"wrong" , success:"right"} %>
  <%= form.text_field :dni, :required => true %>
</div>

<div class="input-field col s12">
  <%= form.label :contact , 'Telefono de Contacto' , :data => {error:"wrong" , success:"right"}  %>
  <%= form.text_field :contact , :required => true %>
</div>

app/views/users/edit.html.erb
<%= form_with(model: @data_model, local: true) do |form| %>
  <div class="card">
    <div class="card-content row">
      <span class="card-title">Editar Datos Personales</span>
      <%= render partial: 'users/personal_info', :locals => {:form => form} %>
      <a id="submit-button" href="#" class="btn-large btn-floating tooltipped halfway-fab waves-effect waves-light orange darken-1" data-position="bottom" data-delay="50" data-tooltip="Guardar Cambios">
        <i class="material-icons">save</i>
      </a>
      <%= form.submit class: 'hide' %>
    </div>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="card">
  <div class="card-content">
    <span class="card-title">Datos de la cuenta</span>
    <p>Email: <%= @email %></p>
    <% unless @personal_info %>
      <a class="btn-large btn-floating tooltipped halfway-fab waves-effect waves-light orange darken-1" data-position="bottom" data-delay="50" data-tooltip="Agregar Datos Personales" href="/users/new_more">
        <i class="material-icons">add</i>
      </a>
    <% end %>
  </div>
  <% if @personal_info %>
    <div class="card-action">
      <p>Nombre: <%= @personal_info.name %></p>
      <p>Apellido: <%= @personal_info.last_name %></p>
      <p>DNI: <%= @personal_info.dni %></p>
      <p>Telefono de Contacto: <%= @personal_info.contact %></p>
      <a class="btn-large btn-floating tooltipped halfway-fab waves-effect waves-light orange darken-1" data-position="bottom" data-delay="50" data-tooltip="Editar" href="<%= edit_personal_information_path(@personal_info)%>">
        <i class="material-icons">edit</i>
      </a>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<%= form_with(model: @data_model, local: true) do |form| %>
  <div class="card">
    <div class="card-content row">
      <span class="card-title">Datos Personales</span>
      <%= render partial: 'users/personal_info', :locals => {:form => form} %>
      <a id="submit-button" href="#" class="btn-large btn-floating tooltipped halfway-fab waves-effect waves-light orange darken-1" data-position="bottom" data-delay="50" data-tooltip="Agregar Datos Personales">
        <i class="material-icons">create</i>
      </a>
      <%= form.submit class: 'hide' %>
    </div>
  </div>
<% end %>

<script type="text/javascript" charset="utf-8">
    $(document).ready(function() {
        $('#submit-button').click(function (e) {
            e.preventDefault();
            $( "input[type='submit']" ).trigger('click')
        })
    });
</script>