config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: {
      sessions: 'users/sessions',
      confirmations: 'users/confirmations'
  }

=begin
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :create, :destroy, :update], defaults: { format: 'json' }
      resources :events, only: [:index, :create, :destroy, :update], defaults: { format: 'json' }
      resources :tasks, only: [:index, :create, :destroy, :update], defaults: { format: 'json' }
      resources :stands, only: [:index, :create, :destroy, :update], defaults: { format: 'json' }
      resources :reserves, only: [:index, :create, :destroy, :update], defaults: { format: 'json' }
      resources :merchants, only: [:index, :create, :destroy, :update], defaults: { format: 'json' }
    end
  end
=end

  root to: 'landing#index'

  resources :events
  #resources :stands
  resources :reserves, only: [:index,:show,:update,:edit,:destroy]
  resources :personal_informations, only: [:create, :new, :edit, :update]
  resources :merchants, only: [:index, :create, :update, :edit, :new]

  post 'events/toggle_stand_auction', to: 'events#toggle_stand_auction'
  get 'events/subscribe/:hash', to: 'events#subscribe_stand'
  get 'reserves/all/:event', to: 'reserves#all'
  get 'reserves/about_to_expire/:id', to: 'reserves#about_to_expire'
  get 'reserves/expire/:id', to: 'reserves#expire'
  post 'reserves/payment', to: 'reserves#payment'

  post 'payment_email', to: 'payments#payment_email'
  post 'payment_upload', to: 'payments#payment_upload'
  get 'payment_status/:id', to: 'payments#payment_status'
  get 'payment_toggle/:id', to: 'payments#payment_toggle'
  get 'payment_confirmation/:id', to: 'payments#payment_confirm'

  get 'mercado_payment/:id', to: 'mercado_pago#status'
  post 'mercado_pago/ipn', to: 'mercado_pago#process_notification'
  get 'mercado_pago/failure', to: 'mercado_pago#failure'
  get 'mercado_pago/success', to: 'mercado_pago#success'
  get 'mercado_pago/pending', to: 'mercado_pago#pending'
  get 'mercado_pago/payment_info/:id', to: 'mercado_pago#get_payment_info_test'

  #get 'tasks', to: 'tasks#dashboard'

  get 'users', to: 'users#index'
  get 'users/new_more', to: 'users#personal_info'

  get 'wizard/:event', to: 'step#step'
  get 'wizard/:event/edit/:step', to: 'step#edit_step'



  get 'landing/institutional', to: 'landing#institutional'
  get 'landing/events', to: 'landing#events'
  get 'landing/multimedia', to: 'landing#multimedia'
  get 'landing/contact', to: 'landing#contact'

  get 'helpers', to: 'landing#helpers'

  get 'token', to: 'mercado_pago#index'
  get 'payment/:id', to: 'mercado_pago#get_payment_info'

  post 'landing/contact', to: 'mailer#contact'

  match "/404", :to => 'errors#not_found', :via => :all
  match "/500", :to => 'errors#internal_server_error', :via => :all
  get 'errors/not_found'
  get 'errors/internal_server_error'

end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :name, presence: true,
            length: { minimum: 2 }
  has_many :tasks
end

app/controllers/api/v1/events_controller.rb
class Api::V1::EventsController < Api::V1::BaseController

  def index
    respond_with Event.all
  end

  def create
    respond_with :api, :v1, Event.create(event_params)
  end

  def destroy
    respond_with Event.destroy(params[:id])
  end

  def update
    event = Event.find(params['id'])
    event.update_attributes(event_params)
    respond_with event, json: event
  end

  private def event_params
    params.require(:event).permit(:id, :name, :release_date)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  layout 'main_app'
  protect_from_forgery with: :null_session
  before_action :authenticate_user!
  before_action :check_privileges! , except: [:subscribe_stand, :index]
  before_action :load_user

  def index
    if (current_user.admin)
      @events = Event.all
    else
      @events = Event.where(stand_auction: true);
    end
  end

  def show
    unless params[:id].nil?
      @event = Event.find_by_id params[:id]
      redirect_to(events_path, :notice => 'Event not found') unless @event
    end
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      generate_hashlinks
      redirect_to @event
    else
      render 'new'
    end
  end

  def new
    @event = Event.new
  end

  def edit
    unless params[:id].nil?
      @event = Event.find_by_id params[:id]
      redirect_to(events_path, :notice => 'Event not found') unless @event
    end
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      flash[:notice] = 'Event was successfully updated.'
      redirect_to @event
    else
      render 'edit'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    redirect_to events_path
  end

  def toggle_stand_auction
    @event = Event.find(params[:event][:id])
    params[:event][:stand_auction] = !@event.stand_auction
    if @event.update(event_params)
      respond_to do |format|
        format.json { render :json => {success: true, stand_auction: @event.stand_auction}}
      end
    else
      respond_to do |format|
        format.json { render :json => {success: false}}
      end
    end
  end

  def subscribe_stand
    redirect_to(events_path, :notice => 'Event link not found') and return if params[:hash].nil?
    hashids = Hashids.new("pandorapp",6)
    event_id = hashids.decode(params[:hash])
    @event = Event.find_by_id event_id

    redirect_to(events_path, :notice => 'No existe ningun evento relacionado.') and return unless @event

    redirect_to(events_path, :notice => 'La convocatoria todavia no ha abierto.') and return unless @event.stand_auction

    @reserve = Reserve.find_by(user_id: current_user.id, event_id: @event.id)
    unless @reserve
      @reserve = Reserve.new(user_id: current_user.id, event_id: @event.id)
      @reserve.save
    end
    redirect_to '/wizard/'+@event.id.to_s
  end

  private def generate_hashlinks
    hashids = Hashids.new("pandorapp",6)
    puts @event.id
    @event.stand_hash_link = hashids.encode(@event.id)
    @event.save
  end

  private def event_params
    params.require(:event).permit(:id, :name, :release_date, :stand_auction , :stand_hash_link, :address, :city, :facebook)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: @event, local: true) do |form| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@event.errors.count, "error") %>
      </h2>
      <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field col s12">
    <%= form.label :name %>
    <%= form.text_field :name , :required => true %>
  </div>

  <div class="input-field col s12">
    <%= form.label :release_date %> <br>
    <%= date_field(:event, :release_date, :required => true ) %>
  </div>

  <div class="input-field col s12">
    <%= form.label :address %>
    <%= form.text_field :address , :required => true %>
  </div>

  <div class="input-field col s12">
    <%= form.label :city %>
    <%= form.text_field :city , :required => true %>
  </div>

  <div class="input-field col s12">
    <%= form.label :facebook %>
    <%= form.text_field :facebook , :required => true %>
  </div>
  <a id="submit-button" href="#" class="btn-large btn-floating tooltipped halfway-fab waves-effect waves-light orange darken-1" data-position="bottom" data-delay="50" data-tooltip="Guardar Cambios">
    <i class="material-icons">save</i>
  </a>
  <%= form.submit class: 'hide' %>
<% end %>

app/views/events/edit.html.erb
<div class="card">
  <div class="card-content row">
    <span class="card-title">Editar Evento</span>
    <%= render 'form' %>
  </div>
</div>

app/views/events/index.html.erb
<%= stylesheet_link_tag 'pages/events'%>
<div class="row">
    <% @events.each do |event| %>
    <div class="col s12 m6">
      <div class="card hoverable">
        <div class="card-content">
          <h5 class="card-title">
            <% if current_user.admin %>
              <a href="<%= event_path(event) %>">
            <% end %>
                <%= event.name %>
            <% if current_user.admin %>
              </a>
            <% end %>
          </h5>
          <p>
            <i class="material-icons">date_range</i>
            <span style="position: relative; top: -4px;"><%= event.release_date %></span>
          </p>
          <p>
            <i class="material-icons">public</i>
            <span style="position: relative; top: -4px;"><a href="<%= event.facebook %>" target="_blank">Evento en Facebook</a></span>
          </p>
          <p>
            <i class="material-icons">location_on</i>
            <span style="position: relative; top: -4px;"><%= event.address %>, <%= event.city %></span>
          </p>

          <br>
          <% if event.stand_auction %>
            <a class="waves-effect waves-light btn orange darken-1" href="<%='/events/subscribe/'+event.stand_hash_link %>">
              <i class="material-icons left">perm_contact_calendar</i>Solicitar Stand
            </a>
          <% end %>
        </div>
          <% if current_user.admin %>
            <a class="btn-floating halfway-fab waves-effect waves-light cyan lighten-3" href="<%= edit_event_path(event) %>">
              <i class="material-icons">edit</i>
            </a>
            <a data-confirm="Estas Seguro?" rel="nofollow" data-method="delete" class="btn-floating halfway-fab waves-effect waves-light red lighten-3 left" href="<%= event_path(event) %>">
              <i class="material-icons">delete</i>
            </a>
          <% end %>
      </div>

    </div>
  <% end %>
</div>

<% if current_user.admin %>
  <div class="fixed-action-btn">
    <a id="scale-demo" href="<%= new_event_path %>" class="btn-floating waves-light waves-effect btn-large scale-transition scale-in" style="background-color: #2d2f78">
      <i class="material-icons">add</i>
    </a>
    <ul class="hide">
      <li><a class="btn-floating red"><i class="material-icons">insert_chart</i></a></li>
      <li><a class="btn-floating yellow darken-1"><i class="material-icons">format_quote</i></a></li>
      <li><a class="btn-floating green"><i class="material-icons">publish</i></a></li>
      <li><a class="btn-floating blue"><i class="material-icons">attach_file</i></a></li>
    </ul>
  </div>
<% end %>


<script type="text/javascript" charset="utf-8">
 $('a').click(function () {
     $(this).removeClass('scale-in');
     $(this).addClass('scale-out');
 })
</script>

app/views/events/new.html.erb
<div class="card">
  <div class="card-content row">
    <span class="card-title">Nuevo Evento</span>
    <%= render 'form' %>
  </div>
</div>

app/views/events/show.html.erb
<div class="card">
  <div class="card-action">
    <span class="card-title"><%=  @event.name %></span>
    <p>
      <i class="material-icons">date_range</i>
      <span style="position: relative; top: -4px;"><%= @event.release_date %></span>
    </p>
    <p> Link Convocatoria: <a href="/events/subscribe/<%= @event.stand_hash_link %>"><%= request.protocol %><%= request.host %>/events/subscribe/<%=  @event.stand_hash_link %></a></p>
    <p>
      <i class="material-icons">public</i>
      <span style="position: relative; top: -4px;"><a href="<%= @event.facebook %>" target="_blank">Evento en Facebook</a></span>
    </p>
    <p>
      <i class="material-icons">location_on</i>
      <span style="position: relative; top: -4px;"><%= @event.address %>, <%= @event.city %></span>
    </p>

    <a id="stands-auction" class="btn-large" data-auction="<% @event.stand_auction %>">
      <% if @event.stand_auction %>
        Detener Convocatoria de Stands
      <% else %>
        Iniciar Convocatoria de Stands
      <% end %>
    </a>
    <%= link_to 'Reservas de Stands', '/reserves/all/'+@event.id.to_s, class: 'btn btn-large' %>
    <br><br>
    <a class="btn-large btn-floating tooltipped halfway-fab waves-effect waves-light orange darken-1" data-position="bottom" data-delay="50" data-tooltip="Editar" href="<%= edit_event_path(@event) %>">
      <i class="material-icons">edit</i>
    </a>
    <a data-confirm="Estas Seguro?" rel="nofollow" data-method="delete" class="btn-large btn-floating tooltipped halfway-fab waves-effect waves-light red left"
       data-position="bottom" data-delay="50" data-tooltip="Borrar Evento" href="<%= event_path(@event) %>">
      <i class="material-icons">delete</i>
    </a>
  </div>
  <%= content_tag :div, class: "event_class", data: {event: @event} do %>
  <% end %>
</div>


<%= javascript_include_tag 'pages/events'%>